# netlify.toml
[build]
  publish = "." # or your actual build output / static folder

[[edge_functions]]
  path = "/event/*"
  function = "share-event"   # maps to /netlify/edge-functions/share-event.{ts,js}

[[edge_functions]]
  path = "/circle/*"
  function = "share-circle"   # maps to /netlify/edge-functions/share-circle.{ts,js}